name: Build

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  build-win:
    name: Build Windows

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          IF EXIST requirements.txt pip install -r requirements.txt
      - name: Build app for Windows
        run: |
          pyinstaller --clean build_windows.spec
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-win
          path: dist/

  build-mac:
    name: Build macOS

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build app for Windows
        run: |
          pyinstaller --clean build_mac.spec
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-mac
          path: dist/
