name: Build

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ windows-latest, macos-latest ]
        include:
          - os: windows-latest
            cache-path: ~\AppData\Local\pip\Cache
            spec-file: build_windows.spec
          - os: macos-latest
            cache-path: ~/Library/Caches/pip
            spec-file: build_mac.spec

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Debug cache folder
        run: |
          echo "$(pip cache dir)"
        shell: bash
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ${{ matrix.cache-path }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
        shell: bash
      - name: Build app
        run: |
          pyinstaller --clean ${{ matrix.spec-file }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: dist/
